server:
  port: 80

email:
  address: www@example.ru

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/practice
    username: postgres
    password: root
  mail:
    host: smtp.gmail.com
    port: 587
    username: <login user to smtp server>
    password: <login password to smtp server>
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true